server:
  port: 8771
spring:
  application:
    name: test-app
  main:
    allow-bean-definition-overriding: true
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  cache:
    type: redis
  mail:
    host: smtp.163.com
    port: 25
    username: 17854117835@163.com
    password: XPDNKIEJRMEJNCTL
    default-encoding: utf-8
    fromMail.address: 17854117835@163.com
    toMail.address: 824131266@qq.com
test:
  schedul:
    enabled: false
logging:
  config: classpath:log4j2-spring.xml
  level:
    com.sitech.ijcf.boot.core: info
#    com.sitech.mybatis.mapper: debug
#    com.bes.enterprise.web.crane.http11: debug

#jcf数据源
jcf:
  datasource:
    A:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jcf3_db?serverTimezone=GMT
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      validationQuery: select 1 from dual;
      defaultAutoCommit: false
  route:
    default-label: A
  core:
    databind-json-type: fastjson

#mybatis配置
mybatis:
  type-aliases-package: com.sitech.wth.entity.mapdto
  mapper-locations: classpath:mybatis/*.xml
ftp:
  server:
    host: 172.18.194.147
    port: 22
    username: orderapp
    password: Oup@2019
    directory: /orderapp/iomApp
