package com.sitech.wth.entity.mapper;

import com.sitech.wth.entity.mapdto.Fruit;
import com.sitech.wth.entity.mapdto.FruitExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated
     */
    long countByExample(FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated
     */
    int deleteByExample(FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated
     */
    int insert(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated
     */
    int insertSelective(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated
     */
    List<Fruit> selectByExample(FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Fruit record, @Param("example") FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Fruit record, @Param("example") FruitExample example);
}