package com.sitech.wth.entity.mapdto;

public class Fruit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruits.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruits.apple
     *
     * @mbg.generated
     */
    private String apple;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruits.banana
     *
     * @mbg.generated
     */
    private String banana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruits.pear
     *
     * @mbg.generated
     */
    private String pear;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruits.id
     *
     * @return the value of fruits.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruits.id
     *
     * @param id the value for fruits.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruits.apple
     *
     * @return the value of fruits.apple
     *
     * @mbg.generated
     */
    public String getApple() {
        return apple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruits.apple
     *
     * @param apple the value for fruits.apple
     *
     * @mbg.generated
     */
    public void setApple(String apple) {
        this.apple = apple == null ? null : apple.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruits.banana
     *
     * @return the value of fruits.banana
     *
     * @mbg.generated
     */
    public String getBanana() {
        return banana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruits.banana
     *
     * @param banana the value for fruits.banana
     *
     * @mbg.generated
     */
    public void setBanana(String banana) {
        this.banana = banana == null ? null : banana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruits.pear
     *
     * @return the value of fruits.pear
     *
     * @mbg.generated
     */
    public String getPear() {
        return pear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruits.pear
     *
     * @param pear the value for fruits.pear
     *
     * @mbg.generated
     */
    public void setPear(String pear) {
        this.pear = pear == null ? null : pear.trim();
    }
}